### ISSUE TITLE
[FIX] Passwordless VNC Connection

### ISSUE THREAD

**Issue by nkpm** [saily/vnc-recorder#12]
Maybe this is of use for someone and might save time.

I'm running a VNC Server without Password. To make this wonderfull tool work i needed to use

`./vnc-recorder -password ""`

Somehow a password is expected.

Thanks for this tool, helps a lot!!

**Comment by saily** [comment]
Hi @nkpm could you provide the error message, did you try `./vnc-recorder --password ""` or first set `export VR_VNC_PASSWORD=""`?

**Comment by lesliezyc123** [comment]
我设置参数为默认值，之后重新编译，可以不需要传--password实现无密码登录
&cli.StringFlag{
				Name:    "password",
				Value:   "",
				Usage:   "Password to connect to the VNC host",
				EnvVars: []string{"VR_VNC_PASSWORD"},
			},

**Comment by saily** [comment]
I did not receive any answer here, so I assume it has been solved already.
