### ISSUE TITLE
Resulting mp4 does not work with Quicktime Player or Windows Media Player

### ISSUE THREAD

**Issue by bdhood** [saily/vnc-recorder#7]
# RS:
Start a VNC server on local machine (or any). I used TightVNC Server
Run vnc-recorder

# Expected:
Resulting mp4 should work with QuickTime Player and Window Media Player

# Actual:
When opening the output mp4 with either player, all I see is a black screen
![Capture](https://user-images.githubusercontent.com/3887673/114257359-165fa880-9985-11eb-8d9a-eef8b3d26acb.PNG)

# Possible resolution:
I have a working solution from https://stackoverflow.com/questions/34942989/ffmpeg-converted-mp4-videos-are-not-playing-on-windows
See MR: https://github.com/saily/vnc-recorder/pull/8
# Windows Media Player: 
![Capture](https://user-images.githubusercontent.com/3887673/114257602-b0742080-9986-11eb-98de-53e977e3d2b7.PNG)
# QuickTime Player:
<img width="710" alt="Screen Shot 2021-04-09 at 10 56 45 PM" src="https://user-images.githubusercontent.com/3887673/114257627-eaddbd80-9986-11eb-8a8f-ce513b6ff7d6.png">

**Comment by saily** [comment]
For now, I'll treat this as solved by #7
